pipeline:
  prepare:
    image: plugins/git
    commands:
      - git clone -b develop https://github.com/mesalock-linux/mesalock-distro.git ../mesalock-distro
  build-packages:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - ./.drone/build-pkgs
  notify:
    image: drillster/drone-email
    secrets: [ plugin_host, plugin_username, plugin_password, plugin_from ]
    when:
      status: [ success, changed, failure ]
