kind: pipeline
name: default

steps:
- name: prepare
  image: plugins/git
  commands:
  - git clone https://github.com/mesalock-linux/mkpkg.git

- name: build-packages
  image: mesalocklinux/build-mesalock-linux
  pull: always
  commands:
  - ./.drone/build-pkgs
