package:
  name: mesapy
  version: 0.1.0
  description: "A memory-safe Python implementation based on PyPy"
  skip_check: true
  license: [BSD]

  source:
    - git+https://github.com/mesalock-linux/mesapy.git

  build:
    - |
      cd mesapy.git
      git submodule update --init
      make

  install:
    - |
      cd mesapy.git

      # Prepare installation (do not package excluded C modules/libraries)
      pypy/tool/release/package.py \
        --archive-name mesapy \
        --targetdir . \
        --without-cffi \
        --rename_pypy_c mesapy
      mkdir unpacked
      tar xf mesapy.tar.bz2 -C unpacked

      # Install pypy
      pushd unpacked
      install -Dm755 mesapy/bin/mesapy "${pkgdir}"/opt/mesapy/bin/mesapy
      install -Dm755 mesapy/bin/libpypy-c.so "${pkgdir}"/opt/mesapy/bin/libpypy-c.so
      install -Dm755 mesapy/bin/libminiz_oxide_c_api.so \
        "${pkgdir}"/opt/mesapy/bin/libminiz_oxide_c_api.so
      cp -r mesapy/include mesapy/lib_pypy mesapy/lib-python mesapy/site-packages "${pkgdir}"/opt/mesapy/
      popd

      # Install symlink
      mkdir -p "${pkgdir}"/usr/bin "${pkgdir}"/usr/lib
      ln -s /opt/mesapy/bin/mesapy "${pkgdir}"/usr/bin/mesapy
      ln -s /opt/mesapy/bin/libminiz_oxide_c_api.so "${pkgdir}"/usr/lib/libminiz_oxide_c_api.so

      # Install misc stuff
      install -Dm644 README.md "${pkgdir}"/opt/mesapy/README.md
      install -Dm644 LICENSE "${pkgdir}"/opt/mesapy/LICENSE
      install -Dm644 LICENSE "${pkgdir}"/usr/share/licenses/mesapy/LICENSE
