package:
  name: tzdata
  version: 1.0.0-2017b
  description: Timezone data
  license: [Unlicense]

  source:
    - https://www.iana.org/time-zones/repository/releases/tzdata2017b.tar.gz

  install:
    - |
      cd tzdata2017b
      timezones="africa antarctica asia australasia \
                 europe northamerica southamerica \
                 pacificnew etcetera backward \
                 systemv factory"
      zic -y ./yearistype -d "${pkgdir}"/usr/share/zoneinfo ${timezones}
      zic -y ./yearistype -d "${pkgdir}"/usr/share/zoneinfo/posix ${timezones}
      zic -y ./yearistype -d "${pkgdir}"/usr/share/zoneinfo/right -L leapseconds ${timezones}
      
      zic -y ./yearistype -d "${pkgdir}"/usr/share/zoneinfo -p America/New_York
      install -m444 -t "${pkgdir}"/usr/share/zoneinfo iso3166.tab zone1970.tab zone.tab # zone.tab is depricated and will go soon