package:
  name: uutils-coreutils
  version: 0.1.0
  description: Cross-platform Rust rewrite of the GNU coreutils
  license: [MIT]
  url: https://github.com/uutils/coreutils
  skip_check: true

  source:
    - git+https://github.com/uutils/coreutils.git

  prepare:
    - cd coreutils.git && git checkout -B 13e57616b41fc3d5fd789bcc95dc46a239473979

  build:
    # skip hashsum and expr because it depends on rust-crypto (with C library)
    - cd coreutils.git && make MULTICALL=y SKIP_UTILS='hashsum expr' PREFIX="$pkgdir" install
