package:
  name: ion-shell
  version: 1.0.5
  description: ion shell, a shell written in Rust
  license: [MIT]
  url: https://github.com/redox-os/ion

  source:
    - git+https://github.com/redox-os/ion.git

  prepare:
    - cd ion.git && git checkout -b 1.0.5

  build:
    - |
      cd ion.git
      cargo update -p liner # make sure liner is updated regardless of Cargo.lock
      cargo +nightly-2018-05-30 install --root "$pkgdir" && rm -f "$pkgdir"/.crates.toml

  install:
    - ln -s ion "$pkgdir"/bin/sh