package:
  name: syslinux
  version: 6.4.0-pre1
  description: Syslinux bootloader
  license: [GPL]
  skip_check: true

  source:
    - https://www.kernel.org/pub/linux/utils/boot/syslinux/Testing/6.04/syslinux-6.04-pre1.tar.xz
    - syslinux.cfg

  build:
    - mkdir install_root
    - cd syslinux-6.04-pre1 && make installer && MAKEFLAGS=-j1 make INSTALLROOT=$builddir/install_root bios efi64 install

  install:
    - |
      for f in isolinux.bin ldlinux.c32 libcom32.c32 libutil.c32 mboot.c32; do
        install -D -m0644 install_root/usr/share/syslinux/"$f" "$pkgdir"/boot/syslinux/"$f"
      done
    - install -D -m0644 syslinux.cfg "$pkgdir"/boot/syslinux/syslinux.cfg
