package:
  name: uutils-findutils
  version: 0.1.0
  description: Rust implementation of findutils
  license: [MIT]
  url: https://github.com/uutils/findutils

  source:
    - git+https://github.com/uutils/findutils.git

  prepare:
    - cd findutils.git && git checkout -B 2e6a268fa5682fc9ee07f8f8b9634051f6c0ef6f

  check:
    - cd findutils.git && cargo test

  install:
    - cd findutils.git && cargo install --root "$pkgdir" && rm -f "$pkgdir"/.crates.toml
